apiVersion: apps/v1
kind: Deployment
metadata:
  name: npool-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npool-scheduler
  template:
    metadata:
      labels:
        app: npool-scheduler
    spec:
      containers:
      - name: npool-scheduler
        image: uhub.service.ucloud.cn/entropypool/npool-scheduler:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: service-config
            mountPath: /etc/NpoolScheduler
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "200Mi"
            cpu: "350m"
          limits:
            memory: "200Mi"
            cpu: "350m"
      volumes:
        - name: service-config
          configMap:
            name: npool-scheduler-config
            items:
              - key: service-conf
                path: NpoolScheduler.viper.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: npool-scheduler
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 50800
    targetPort: 50800
  - name: grpc
    port: 50801
    targetPort: 50801
  - name: prometheus
    port: 50802
    targetPort: 50802
  selector:
    app: npool-scheduler
