// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package npool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CloudHashingStakerClient is the client API for CloudHashingStaker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudHashingStakerClient interface {
	// Method Version
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type cloudHashingStakerClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudHashingStakerClient(cc grpc.ClientConnInterface) CloudHashingStakerClient {
	return &cloudHashingStakerClient{cc}
}

func (c *cloudHashingStakerClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/cloud.hashing.staker.v1.CloudHashingStaker/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudHashingStakerServer is the server API for CloudHashingStaker service.
// All implementations must embed UnimplementedCloudHashingStakerServer
// for forward compatibility
type CloudHashingStakerServer interface {
	// Method Version
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedCloudHashingStakerServer()
}

// UnimplementedCloudHashingStakerServer must be embedded to have forward compatible implementations.
type UnimplementedCloudHashingStakerServer struct {
}

func (UnimplementedCloudHashingStakerServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedCloudHashingStakerServer) mustEmbedUnimplementedCloudHashingStakerServer() {}

// UnsafeCloudHashingStakerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudHashingStakerServer will
// result in compilation errors.
type UnsafeCloudHashingStakerServer interface {
	mustEmbedUnimplementedCloudHashingStakerServer()
}

func RegisterCloudHashingStakerServer(s grpc.ServiceRegistrar, srv CloudHashingStakerServer) {
	s.RegisterService(&CloudHashingStaker_ServiceDesc, srv)
}

func _CloudHashingStaker_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudHashingStakerServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.hashing.staker.v1.CloudHashingStaker/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudHashingStakerServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudHashingStaker_ServiceDesc is the grpc.ServiceDesc for CloudHashingStaker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudHashingStaker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.hashing.staker.v1.CloudHashingStaker",
	HandlerType: (*CloudHashingStakerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _CloudHashingStaker_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/cloud-hashing-staker.proto",
}
